n01569183PetProject/Controllers/PlayerController.cs
using n01569183PetProject.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace n01569183PetProject.Controllers
{
    public class PlayerController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static PlayerController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44391/api/");
        }
        // GET: Player
        public ActionResult Index()
        {
            return Redirect("List");
        }

        // GET: Player/List
        public ActionResult List()
        {
            string url = "PlayerData/ListPlayers";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<Player> Players = response.Content.ReadAsAsync<IEnumerable<Player>>().Result;
            return View(Players);
        }

        // GET: Player/Show/3
        [Authorize]
        public ActionResult Show(int id)
        {
            string url = "PlayerData/FindPlayer/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Player Player = response.Content.ReadAsAsync<Player>().Result;

            return View(Player);

        }

        // GET: Player/ToggleState/3
        public ActionResult ToggleState(int id)
        {
            string url = "PlayerData/ToggleLiveState/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            return Redirect("/Player/List");

        }

        // GET: Player/New

        [Authorize]
        public ActionResult New()
        {
            GetApplicationCookie();
            string url = "TeamData/ListTeamsWithRoles";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<TeamDto> Teams = response.Content.ReadAsAsync<IEnumerable<TeamDto>>().Result;
            return View(Teams);
        }

        // POST: Player/Save
        // BODY: Player
        [Authorize]
        [HttpPost]
        public ActionResult Save(Player Player)
        {
            GetApplicationCookie();
            string url = "PlayerData/UpdatePlayer/" + Player.PlayerId;
            HttpContent content = Prepare(Player);
            Debug.WriteLine(Player.PlayerScore);
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            return Redirect("/Player/list");


        }

        // POST: Player/Add
        // BODY: Player
        [Authorize]
        public ActionResult Add(Player Player)
        {
            GetApplicationCookie();
            string url = "PlayerData/AddPlayer";
            HttpContent content = Prepare(Player);
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            return Redirect("/Player/list");

        }


        // GET: Player/ConfirmDelete/3
        public ActionResult ConfirmDelete(int id)
        {
            string url = "PlayerData/FindPlayer/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Player Player = response.Content.ReadAsAsync<Player>().Result;

            return View(Player);
        }

        // POST: Player/Delete/3
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int PlayerId)
        {
            GetApplicationCookie();
            string url = "PlayerData/DeletePlayer/" + PlayerId;
            HttpResponseMessage response = client.GetAsync(url).Result;
            return Redirect("/Player/List");
        }

        // POST: Player/Submit
        // BODY: Player
        [Authorize]
        public ActionResult Submit(Player Player)
        {
            GetApplicationCookie();
            string url = "PlayerData/AddPlayer";
            HttpContent content = Prepare(Player);
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            return Redirect("/Player/list");
        }

        // Prepares a JSON playload
        private HttpContent Prepare(Player Player)
        {
            string jsonpayload = jss.Serialize(Player);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            return content;
        }

        private void GetApplicationCookie()
        {
            string token = "";
            //HTTP client is set up to be reused, otherwise it will exhaust server resources.
            //This is a bit dangerous because a previously authenticated cookie could be cached for
            //a follow-up request from someone else. Reset cookies in HTTP client before grabbing a new one.
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //collect token as it is submitted to the controller
            //use it to pass along to the WebAPI.
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }
    }
}

n01569183PetProject/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Web.Script.Serialization;
using n01569183PetProject.Models;
using System.Diagnostics;

namespace n01569183PetProject.Controllers
{
    public class RoleController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static RoleController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                //cookies are manually set in RequestHeader
                UseCookies = false
            };

            client = new HttpClient(handler);
            client.BaseAddress = new Uri("https://localhost:44391/api/");
        }
        private void GetApplicationCookie()
        {
            string token = "";
            //HTTP client is set up to be reused, otherwise it will exhaust server resources.
            //This is a bit dangerous because a previously authenticated cookie could be cached for
            //a follow-up request from someone else. Reset cookies in HTTP client before grabbing a new one.
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //collect token as it is submitted to the controller
            //use it to pass along to the WebAPI.
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }

        // GET: Role
        public ActionResult Index()
        {
            return Redirect("List");
        }

        // GET: Role/List

        public ActionResult List()
        {
            string url = "RoleData/ListRoles";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<Role> Roles = response.Content.ReadAsAsync<IEnumerable<Role>>().Result;
            return View(Roles);
        }


        // GET: Role/Show/2

        public ActionResult Show(int id)
        {
            string url = "RoleData/FindRole/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            RoleDto Role = response.Content.ReadAsAsync<RoleDto>().Result;
            return View(Role);

        }

        // GET: Role/Update/2

        [HttpGet]
        [Authorize]
        public ActionResult Update(int id)
        {
            GetApplicationCookie();
            string url = "RoleData/FindRole/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            RoleDto Role = response.Content.ReadAsAsync<RoleDto>().Result;

            return View(Role);

        }

        // GET: Role/New

        [Authorize]
        public ActionResult New()
        {
            GetApplicationCookie();
            string url = "TeamData/ListTeams";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<Team> Teams = response.Content.ReadAsAsync<IEnumerable<Team>>().Result;
            return View(Teams);
        }

        // POST: Role/Save
        // BODY: Role, RoleIcon
        [Authorize]
        [HttpPost]
        public ActionResult Save(Role Role, HttpPostedFileBase RoleIcon)
        {
            GetApplicationCookie();
            string url = "RoleData/UpdateRole/" + Role.RoleId;
            HttpContent content = Prepare(Role);
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if(RoleIcon != null)
            {
                url = "RoleData/UploadRoleImg/" + Role.RoleId;

                MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                HttpContent imagecontent = new StreamContent(RoleIcon.InputStream);
                requestcontent.Add(imagecontent, "roleImg", RoleIcon.FileName);
                response = client.PostAsync(url, requestcontent).Result;

            }


            return Redirect("/Role/list");


        }

        // GET: Role/ConfirmDelete/2

        public ActionResult ConfirmDelete(int id)
        {
            string url = "RoleData/FindRole/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Role Role = response.Content.ReadAsAsync<Role>().Result;

            return View(Role);
        }

        // POST: Role/Delete/2
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int RoleId)
        {
            string url = "RoleData/DeleteRole/" + RoleId;
            HttpResponseMessage response = client.GetAsync(url).Result;
            return Redirect("/Role/List");
        }

        // Prepares a JSON playload

        private HttpContent Prepare(Role role)
        {
            string jsonpayload = jss.Serialize(role);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            return content;
        }
    }
}

n01569183PetProject/Controllers/TeamController.cs
using n01569183PetProject.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace n01569183PetProject.Controllers
{
    public class TeamController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static TeamController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44391/api/");
        }

        // GET: Team/New
        [Authorize]
        public ActionResult New()
        {
            GetApplicationCookie();
            return View();
        }

        // GET: Team/List
        public ActionResult List()
        {
            string url = "TeamData/ListTeams";
            HttpResponseMessage response = client.GetAsync(url).Result;

            IEnumerable<Team> Teams = response.Content.ReadAsAsync<IEnumerable<Team>>().Result;
            return View(Teams);
        }
        // GET: Team/Show/3

        public ActionResult Show(int id)
        {
            string url = "TeamData/FindTeamWithRoles/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            TeamDto Team = response.Content.ReadAsAsync<TeamDto>().Result;

            return View(Team);

        }

        // GET: Team/Update/3

        [Authorize]
        public ActionResult Update(int id)
        {
            GetApplicationCookie();

            string url = "TeamData/FindTeamWithRoles/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            TeamDto Team = response.Content.ReadAsAsync<TeamDto>().Result;

            return View(Team);

        }

        // GET: Team/ConfirmDelete/3
        public ActionResult ConfirmDelete(int id)
        {
            string url = "TeamData/FindTeam/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            TeamDto Team = response.Content.ReadAsAsync<TeamDto>().Result;

            return View(Team);
        }

        // GET: Team/Delete/3
        [Authorize]
        public ActionResult Delete(int TeamId)
        {
            string url = "TeamData/DeleteTeam/" + TeamId;
            HttpResponseMessage response = client.GetAsync(url).Result;
            return Redirect("/Team/List");
        }

        // POST: Team/Add
        // BODY: Team

        [HttpPost]
        [Authorize]
        public ActionResult Add(string TeamName, string TeamWinCondition, string TeamDescription, string TeamColor)
        {
            GetApplicationCookie();

            string url = "TeamData/AddTeam";

            Team Team = new Team()
            {
                TeamName = TeamName,
                TeamWinCondition = TeamWinCondition,
                TeamColor = TeamColor,
                TeamDescription = TeamDescription,
            };

            string jsonpayload = jss.Serialize(Team);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            return Redirect("/Team/List");
        }


        // POST: Team/Save
        // BODY: Team, TeamIcon

        [Authorize]

        public ActionResult Save(Team Team, HttpPostedFileBase TeamIcon)
        {

            GetApplicationCookie();

            string jsonpayload = jss.Serialize(Team);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            string url = "TeamData/UpdateTeam/" + Team.TeamId;
            HttpResponseMessage response = client.PostAsync(url, content).Result;


            if (TeamIcon != null)
            {
                Debug.Write("Uploading Team image...");
                url = "TeamData/UploadTeamImg/" + Team.TeamId;

                MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                HttpContent imagecontent = new StreamContent(TeamIcon.InputStream);
                requestcontent.Add(imagecontent, "teamImg", TeamIcon.FileName);
                response = client.PostAsync(url, requestcontent).Result;

            }


            return Redirect("Show/"+ Team.TeamId);
        }

        private void GetApplicationCookie()
        {
            string token = "";
            //HTTP client is set up to be reused, otherwise it will exhaust server resources.
            //This is a bit dangerous because a previously authenticated cookie could be cached for
            //a follow-up request from someone else. Reset cookies in HTTP client before grabbing a new one.
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //collect token as it is submitted to the controller
            //use it to pass along to the WebAPI.
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }
    }
}

n01569183PetProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mafia</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mafia", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Teams", "List", "Team")</li>
                        <li>@Html.ActionLink("Roles", "List", "Role")</li>
                        <li>@Html.ActionLink("Players", "List", "Player")</li>
                        <li>@Html.ActionLink("Game", "Index", "Game")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Game", "Player", "Game")</li>

                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Shavin Singh</p>
        </footer>
    </div>

    <div id="PopupBox" class="popup hidden">
        <p>Popup Box</p>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        function gid(id) {
            return document.getElementById(id);
        }

        async function api(endpoint, callback = () => { }) {
            var url = location.origin + "/api/" + endpoint;
            var xhr = new XMLHttpRequest();
            xhr.open("get", url, true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    if (xhr.status === 200) {
                        var res;
                        try {
                            res = JSON.parse(xhr.response);
                        }
                        catch { }
                        callback(res);
                    }
                    else callback(null);;
                }

            }
            xhr.send(null);
        }

        async function apip(endpoint, payload, callback = () => { }) {
            var url = location.origin + "/api/" + endpoint;
            var xhr = new XMLHttpRequest();

            xhr.open("post", url, true);

            xhr.setRequestHeader("Content-Type", "application/json");
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    if (xhr.status === 200) {
                        var response;
                        try {
                            response = JSON.parse(xhr.response);
                        } catch {
                            response = null;
                        }
                        callback(response);
                    }
                    else callback(null);;
                }

            }
            xhr.send(JSON.stringify(payload));
        }

        function popup(url) {
            var xhr = new XMLHttpRequest();
            xhr.open('get', url, true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    display('PopupBox', xhr.response);
                }
            }
            xhr.send(null);
        }

        function display(id, content) {
            document.getElementById(id).innerHTML = content;
            document.getElementById(id).classList.remove('hidden');
        }

        function cancelPopup() {
            document.getElementById("PopupBox").classList.add('hidden');
        }
    </script>
</body>
</html>